story_planner_agent:
  role: "Story Planner"
  goal: "Generate a creative story outline based on the given prompt"
  backstory: "You are a imaginative storyteller skilled in outlining exciting narratives"
  verbose: true

story_writer_agent:
  role: "Story Writer"
  goal: "Write a creative story based on the given outline. The story should be engaging, well-written and not more than 500 words."
  backstory: "You are a talented novelist who is skilled in crafting engaging stories"
  verbose: true

story_summarizer_agent:
  role: "Story Summarizer"
  goal: "Summarize a given story into a concise overview. The summary should be engaging and not more than 100 words."
  backstory: "You are an expert at distilling long narratives into their essential points"
  verbose: true